In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv("C:/Users/HP/Downloads/PM_Modi_Speech_Cleaned_string.csv")

In [3]:
df_data

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string
0,0,2,09 JAN 2017,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...
1,1,3,09 JAN 2017,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...
2,2,5,03 JAN 2017,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...
3,3,6,26 FEB 2017,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...
4,4,8,21 FEB 2017,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...
...,...,...,...,...,...,...,...
1177,1177,1263,08 APR 2023,Bharat Mata Ki Jai!\n\nBharat Mata Ki Jai!\n\n...,English rendering of PM’s address at launch of...,"['bharat mata ki jai', 'bharat mata ki jai', '...",bharat mata ki jai bharat mata ki jai governor...
1178,1178,1264,04 APR 2023,ExcellenciesHonourable Minister Mr. Harbers;Sp...,"Text of Address by Dr. P.K. Mishra, Principal ...",['excellencieshonourable minister mr harbers s...,excellencieshonourable minister mr harbers spe...
1179,1179,1265,04 APR 2023,"Namaskar!Excellencies, heads of state, Academi...",Text of PM’s remarks at International Conferen...,['namaskar excellency head state academic busi...,namaskar excellency head state academic busine...
1180,1180,1266,03 APR 2023,My colleague in the Union Cabinet Dr. Jitendra...,English rendering of PM’S address at the diamo...,['colleague union cabinet dr jitendra singh ji...,colleague union cabinet dr jitendra singh ji n...
1181,1181,1267,01 APR 2023,Bharat Mata Ki Jai!Bharat Mata Ki Jai!The Gove...,English rendering of PM’s speech at flagging o...,['bharat mata ki jai bharat mata ki jai govern...,bharat mata ki jai bharat mata ki jai governor...

In [5]:
dummy = df_data.iloc[:10].copy()
dummy

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string
0,0,2,09 JAN 2017,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...
1,1,3,09 JAN 2017,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...
2,2,5,03 JAN 2017,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...
3,3,6,26 FEB 2017,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...
4,4,8,21 FEB 2017,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...
5,5,10,05 FEB 2017,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...
6,6,11,01 FEB 2017,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...
7,7,13,26 MAR 2017,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...
8,8,16,18 MAR 2017,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...
9,9,17,09 MAR 2017,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...

In [6]:
dummy.drop("Unnamed: 0.1", axis = 1)

,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string
0,2,09 JAN 2017,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...
1,3,09 JAN 2017,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...
2,5,03 JAN 2017,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...
3,6,26 FEB 2017,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...
4,8,21 FEB 2017,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...
5,10,05 FEB 2017,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...
6,11,01 FEB 2017,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...
7,13,26 MAR 2017,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...
8,16,18 MAR 2017,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...
9,17,09 MAR 2017,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...

In [6]:
from datetime import datetime
month_dict = {
    "JAN": "01",
    "FEB": "02",
    "MAR": "03",
    "APR": "04",
    "MAY": "05",
    "JUN": "06",
    "JUL": "07",
    "AUG": "08",
    "SEP": "09",
    "OCT": "10",
    "NOV": "11",
    "DEC": "12"
}

def dates(x):
    dt = datetime.strptime(x, "%d %b %Y")
    #month_num = month_dict[(dt.strftime("%b")).upper()]
    #new_date_str = dt.strftime("%d-%m-%Y").replace(dt.strftime("%b"), month_num)
    return dt

In [7]:
dummy['Date'] = dummy['Date'].apply(dates)

In [8]:
dummy

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string
0,0,2,2017-01-09,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...
1,1,3,2017-01-09,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...
2,2,5,2017-01-03,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...
3,3,6,2017-02-26,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...
4,4,8,2017-02-21,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...
5,5,10,2017-02-05,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...
6,6,11,2017-02-01,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...
7,7,13,2017-03-26,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...
8,8,16,2017-03-18,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...
9,9,17,2017-03-09,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...

In [10]:
dummy = dummy.sort_values('Date')

In [11]:
dummy

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string
2,2,5,2017-01-03,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...
0,0,2,2017-01-09,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...
1,1,3,2017-01-09,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...
6,6,11,2017-02-01,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...
5,5,10,2017-02-05,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...
4,4,8,2017-02-21,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...
3,3,6,2017-02-26,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...
9,9,17,2017-03-09,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...
8,8,16,2017-03-18,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...
7,7,13,2017-03-26,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...

In [24]:
#changing the index
new_index = ['NMS' + str(i) for i in range(1, len(dummy)+1)]
#renaming to reflect on df
dummy = dummy.rename(index=dict(zip(dummy.index, new_index)))
dummy

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string,ID
NMS1,2,5,2017-01-03,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...,NMS1
NMS2,0,2,2017-01-09,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...,NMS2
NMS3,1,3,2017-01-09,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...,NMS3
NMS4,6,11,2017-02-01,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...,NMS4
NMS5,5,10,2017-02-05,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...,NMS5
NMS6,4,8,2017-02-21,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...,NMS6
NMS7,3,6,2017-02-26,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...,NMS7
NMS8,9,17,2017-03-09,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...,NMS8
NMS9,8,16,2017-03-18,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...,NMS9
NMS10,7,13,2017-03-26,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...,NMS10

In [ ]:
dummy

In [13]:
dummy = dummy.assign(ID=['NMS{}'.format(i) for i in range(1, len(dummy)+1)])
dummy

,Unnamed: 0.1,Unnamed: 0,Date,Speech,Title,Cleaned_Speech,Cleaned_Speech_string,ID
2,2,5,2017-01-03,"Governor of Andhra Pradesh, Shri E. S. L. Nara...",PM's Address at the Inauguration of the 104th ...,['governor andhra pradesh shri e l narasimhan ...,governor andhra pradesh shri e l narasimhan ch...,NMS1
0,0,2,2017-01-09,Chief Minister of Gujarat Shri Vijay Rupani ji...,Text of PM's address at the Inauguration of No...,['chief minister gujarat shri vijay rupani ji ...,chief minister gujarat shri vijay rupani ji co...,NMS2
1,1,3,2017-01-09,I am delighted to be here at Gift City to ina...,Text of PM’s address on the occasion of Inaugu...,['delighted gift city inaugurate india first i...,delighted gift city inaugurate india first int...,NMS3
6,6,11,2017-02-01,I congratulate the Finance Minister Arun Jaitl...,English rendering of the Prime Minister’s Stat...,['congratulate finance minister arun jaitley j...,congratulate finance minister arun jaitley jee...,NMS4
5,5,10,2017-02-05,Sri Pejavar Math’s most respected Sri Vishwesh...,English rendering of the text of PM’s address ...,['sri pejavar math respected sri vishwesh tirt...,sri pejavar math respected sri vishwesh tirth ...,NMS5
4,4,8,2017-02-21,Namaskaram. Greetings to everyone. Swami Nirvi...,Text of PM’s inaugural address (via video conf...,"['namaskaram', 'greeting everyone', 'swami nir...",namaskaram greeting everyone swami nirvinanand...,NMS6
3,3,6,2017-02-26,"My dear countrymen, Namaskar. Winter is on its...",English Translation of the text of PM’s ‘Mann ...,"['dear countryman namaskar', 'winter way', 'va...",dear countryman namaskar winter way vasant sea...,NMS7
9,9,17,2017-03-09,"Welcome friends, \n\nAll of us are back togeth...",English rendering of the Prime Minister Shri N...,['welcome friend u back together recess budget...,welcome friend u back together recess budget s...,NMS8
8,8,16,2017-03-18,"First of all, many-many congratulations and gr...",English Rendering of PM’s address (through vid...,['first many many congratulation greeting orga...,first many many congratulation greeting organi...,NMS9
7,7,13,2017-03-26,"My dear countrymen, Namaskar. Parents in most ...",English Translation of the Text of ‘Mann Ki Ba...,"['dear countryman namaskar', 'parent part coun...",dear countryman namaskar parent part country m...,NMS10

In [22]:
dummy.reset_index()
dummy = dummy.drop('columns=Unnamed')

KeyError: "['columns=Unnamed'] not found in axis"

In [144]:
import numpy as np
from datetime import datetime

##Individual code for sorting dates

In [145]:
date_array = dummy['Date'].values

In [146]:
date_array

array(['09 JAN 2017', '09 JAN 2017', '03 JAN 2017', '26 FEB 2017',
       '21 FEB 2017', '05 FEB 2017', '01 FEB 2017', '26 MAR 2017',
       '18 MAR 2017', '09 MAR 2017'], dtype=object)

In [147]:
datetime_dates = np.array([datetime.strptime(d, '%d %b %Y') for d in date_array])

In [148]:
datetime_dates

array([datetime.datetime(2017, 1, 9, 0, 0),
       datetime.datetime(2017, 1, 9, 0, 0),
       datetime.datetime(2017, 1, 3, 0, 0),
       datetime.datetime(2017, 2, 26, 0, 0),
       datetime.datetime(2017, 2, 21, 0, 0),
       datetime.datetime(2017, 2, 5, 0, 0),
       datetime.datetime(2017, 2, 1, 0, 0),
       datetime.datetime(2017, 3, 26, 0, 0),
       datetime.datetime(2017, 3, 18, 0, 0),
       datetime.datetime(2017, 3, 9, 0, 0)], dtype=object)

In [149]:
sorted_indices = np.argsort(datetime_dates)

In [150]:
sorted_indices

array([2, 0, 1, 6, 5, 4, 3, 9, 8, 7], dtype=int64)

In [151]:
sorted_dates = dates[sorted_indices]

In [164]:
sorted_dates

2    03 JAN 2017
0    09 JAN 2017
1    09 JAN 2017
6    01 FEB 2017
5    05 FEB 2017
4    21 FEB 2017
3    26 FEB 2017
9    09 MAR 2017
8    18 MAR 2017
7    26 MAR 2017
Name: Date, dtype: object

In [152]:
print(sorted_dates)

2    03 JAN 2017
0    09 JAN 2017
1    09 JAN 2017
6    01 FEB 2017
5    05 FEB 2017
4    21 FEB 2017
3    26 FEB 2017
9    09 MAR 2017
8    18 MAR 2017
7    26 MAR 2017
Name: Date, dtype: object

##Writing the function and loop for the entire date column

In [181]:
Dates = dummy.Date
def Sorting_dates(Dates):
    for i in Dates:
        d = i.values
        datetime_dates = np.array([datetime.strptime(d, '%d %b %Y') for i in Dates])
        sorted_indices = np.argsort(datetime_dates)
        sorted_dates = dates[sorted_indices]
    return(sorted_dates)

In [182]:
dummy["Date"].apply(Sorting_dates)

AttributeError: 'str' object has no attribute 'values'

In [160]:
Dates

0    09 JAN 2017
1    09 JAN 2017
2    03 JAN 2017
3    26 FEB 2017
4    21 FEB 2017
5    05 FEB 2017
6    01 FEB 2017
7    26 MAR 2017
8    18 MAR 2017
9    09 MAR 2017
Name: Date, dtype: object

In [161]:
Dates.apply(Sorting_dates)

AttributeError: 'str' object has no attribute 'values'

In [162]:
Dates = dummy.Date

def Sorting_dates(Dates):
    for i in Dates:
        d = i
        datetime_obj = np.array([datetime.strptime(d, '%d %b %Y') for d in Dates])
        sorted_indices = np.argsort(datetime_obj)
        sorted_dates = Dates[sorted_indices]
    return sorted_dates

sorted_dates = Sorting_dates(Dates)
print(sorted_dates)

2    03 JAN 2017
0    09 JAN 2017
1    09 JAN 2017
6    01 FEB 2017
5    05 FEB 2017
4    21 FEB 2017
3    26 FEB 2017
9    09 MAR 2017
8    18 MAR 2017
7    26 MAR 2017
Name: Date, dtype: object

In [163]:
Dates.apply(Sorting_dates)

ValueError: time data '0' does not match format '%d %b %Y'

In [ ]:
from datetime import datetime

In [ ]:
Date = df_data['Date']

In [ ]:
def sort_dates(Date):
    # Define a key function that converts a date string to a datetime object
    def date_key(Date):
        return datetime.strptime(Date, '%d %b %Y')
     
    # Use the sorted function to sort the list of dates, using the date_key function as the key
    return sorted(Date, key=Date)

In [ ]:
Date = df_data['Date'].apply(sort_dates)

In [ ]:
import datetime
def sort_date (Date):
    sortedDates = sorted([datetime.datetime.strptime(i, '%d %b %Y') for i in Date])
    [i.strftime('%d %b %Y') for i in sortedDates]

In [ ]:
df_data['Date'].apply(sort_date)

In [ ]:
my_tuple = tuple(df_data['Date'])
my_dict = {my_tuple: 'Dates'}
my_set = set([my_tuple])
sorted_dates = sorted(my_set)

In [ ]:
sorted_dates

In [ ]:
import pandas as pd

# Create a sample DataFrame with dates in object format
df = df_data.Date

# Convert the 'Date' column to a datetime object
df = pd.to_datetime(df, format='%d %b %Y')

# Sort the DataFrame by the 'Date' column in ascending order
df_data = df.sort_values(df)

print(df)

In [ ]:
sort_date = df_data.Date
sort_date

In [ ]:
type(sort_date)

In [ ]:
def convert_date(Date):
    for i in sort_date:
        datetime.strptime(sort_date, '%d %b %Y')
    sorted_dates = sorted(sort_date, key=convert_date)
    return(sorted_dates)

In [ ]:
from datetime import datetime

def convert_date(date_str):
    for i in sort_date:
        datetime.strptime(sort_date, '%d %b %Y')
    sorted_dates = df_data['Date'].apply(convert_date).sort_values()
    return(sorted_dates)

In [ ]:
Date = df_data['Date'].apply(convert_date)

In [ ]:
Date = df_data['Date'].apply(convert_date)

In [ ]:
from datetime import datetime

def convert_date(date_str):
    return datetime.strptime(date_str, '%d %b %Y')

sorted_dates = df_data['Date'].apply(convert_date).sort_values()

In [ ]:
Speech_List = df_data["Cleaned_Speech_string"]

In [ ]:
def IDS(Speech_List):
    Uni_Id = []
    for i in Speech_List:
        Id = id(i)
        Uni_Id.append(Id)
    return Uni_Id

In [ ]:
Id

In [ ]:
print("id of var_1 : ", id(var1))